import type { Metadata } from "next";
import "./globals.css";

import Navigation from "./nav";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-offwhite flex flex-col h-screen">
        <Navigation />
        <div className="flex-1  ">{children}</div>
        <div className="flex-end ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
